name: yamdb-main

on:
  push:
    branches:
    - main
env:
  TEST_PROJECT_PATH: YAMDB.Tests/YAMDB.Tests.csproj
  CORE_PROJECT_PATH: YAMDB
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x  
    
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest    
        
    steps:            
    - name: Checkout            
      uses: actions/checkout@v3
      
    - name: Setup dotnet ${{ env.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}
        
    - name: Restore
      run: dotnet restore
      
    - name: Build & Publish
      run: dotnet publish --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Set Secret Token
      run: dotnet user-secrets set "DOPPLER_TOKEN" "${{ secrets.DOPPLER_PROD_TOKEN }}" --project "${{ env.CORE_PROJECT_PATH }}"
      
    - name: Test
      run: dotnet test ${{ env.TEST_PROJECT_PATH }} --no-restore --verbosity normal
